### ISSUE TITLE
Build a Salesforce Glossary for Sales

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#370]
Build a glossary per object where Salesforce users can consult the most relevant/use fields to build reporting, etc.

Biz-Ops doc as a reference for guidance: https://docs.google.com/spreadsheets/d/1-LsjHAdBr55RYab3JijIiuS4hBrvAEh4eOcvPNbF2zk/edit#gid=1424742329

@FloBroderick for awareness

**Comment by MiriamMartinezNunez** [comment]
[Moved to Shortcut](https://app.shortcut.com/cartoteam/story/427030/build-a-data-dictionary)
