### ISSUE TITLE
OLD Leads deletion

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#371]
Drive folder: https://drive.google.com/drive/u/0/folders/1N8bxFzPebrRsmV8jCHLJutPvIF59LjQe

Report1: [https://docs.google.com/spreadsheets/d/1EZ8HTyXWueOah22X69GMwFFq3QxS67-0cfzD114sUYc/edit#gid=541820246](https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1EZ8HTyXWueOah22X69GMwFFq3QxS67-0cfzD114sUYc/edit%23gid%3D541820246&sa=D&source=calendar&ust=1684918350601164&usg=AOvVaw1nGcV7Ej6FcMpBhoj2fx9b) (pendiente de oK)
[https://carto.lightning.force.com/lightning/r/Report/00O1v000008jOq7EAE/view](https://www.google.com/url?q=https://carto.lightning.force.com/lightning/r/Report/00O1v000008jOq7EAE/view&sa=D&source=calendar&ust=1684918350601164&usg=AOvVaw0BgjgXpJMdkQdVbDPa5w5N)

**Comment by MiriamMartinezNunez** [comment]
[Moved to Shortcut](https://app.shortcut.com/cartoteam/story/427738)
