### ISSUE TITLE
Suger set up & SF integration (replace Tackle)

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#374]
Checklist: 

https://docs.google.com/document/d/1S5eX-7h05btjzKOLgzWyuy866mL1QSui7J5rLXqMwrw/edit

**Comment by ruipperez** [comment]
Currently on hold until new version is tested by Suger.

Drive folder for reference: https://drive.google.com/drive/u/0/folders/1dJNSkFfu0J-CEr8lCWA-af-Id0i8oo0h

**Comment by ruipperez** [comment]
Suger confirmed this week their app is ready to be re-installed

**Comment by MiriamMartinezNunez** [comment]
Moved to Shortcut https://app.shortcut.com/cartoteam/story/427659
