### ISSUE TITLE
CPQ tools

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#380]
Explore CPQ tools to improve existing pricing and quotation process, especially for data deals.

Tools being explored:

- [ ] [DealHub](https://dealhub.io/)
- [ ]  [Subskribe](https://www.subskribe.com/) - custom demo Monday 4th
- [ ] Salesforce CPQ module - demo Monday 4th Dec
- [x] Retool - discarded

**Comment by MiriamMartinezNunez** [comment]
[Moved to Shortcut](https://app.shortcut.com/cartoteam/story/427719)
