### ISSUE TITLE
Marketing Metrics update

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#384]
Working doc: https://docs.google.com/document/d/1D1ZW_F1epileowXeDt3HQFdLwTFnSO6gBOQ9Mln8GHs/edit#heading=h.jxmvh5s5lwe6

1. Analysis of % conversion MQL → Contacted → First Meeting → Opp - Victor

2. Confirm scope of new business: Do MQLs include both existing and new logos (logos given at the subsidiary level)? Can we separate them out in the dash? - Laura

3. Add filters to dash - Victor/Miri

4. Add data to dash - Victor/Miri

5. Operationalize enlarged attribution of lead to account - Laura. Pending their evaluation on resources e.g. engineer, hours, development, testing. Laura will let us know when Omega has an update

**Comment by ruipperez** [comment]
This project is being led by Ivicuo in partnership with Biz-Ops and @victorfolque

**Comment by MiriamMartinezNunez** [comment]
Moved to Shortcut [https://app.shortcut.com/cartoteam/story/427333/marketing-metrics-update]
Closing here
