### ISSUE TITLE
Account Mapping solutions

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#385]
Account Mapping tools explored by Leo to integrate with SF:

Prolifiq: [Link to Demo Recording from 3/15](https://d2rswj04.na1.hs-sales-engage.com/Ctc/W3+23284/d2rSWj04/Jll2-6qcW7Y8-PT6lZ3n4W2NC74Y78w6CzN65PH1mcLg8YW1Dj_Yn1kxxMjN1Rr2NSCPfXtN1sMbgV14F4FW13Gcp17WN5x6W5yWknH8xGXrjW45xg4y5GvzXDW6YbC9g8xXlDsN32Y_sNJ07KjW8Ql6GN4lB-51W7WRk812rd-xCVZ1cB86rPkWwW5bnctB3kQW3JW4hz4cv7TcfXMV9_1_K6FMwQkW51Z4sJ552--vW7Xppgl2V5z4SW8NHvMw1TzYVCW52CZwc8PJJ6VMfq0HZyR1PWW9gzXFh3PZWssV2533m43G3rlVhk4v-32LWDRW6R-vgB1KxcB4W8hh4dn8r8SjDf1ZHMcz04)
People.ai: [Call Recording](https://t.yesware.com/tt/0aa0bce4582a70f264941e8f3eaeef41e4e9d65d/e1f4f126a42342fd90f40f7e34db391f/d45a624aa0a51bca700121d12109ccae/peopleai.zoom.us/rec/share/mZyZtGfSgq9XG7yixkgeNzs3hh050_WnXPRuzuIchC1CsmihBeWYao-tjf6S9l9q.-b0rEYLqYwwCBQL7) - Passcode: qF&28p+!

**Comment by MiriamMartinezNunez** [comment]
Already moved with People.ai
Closing here
