### ISSUE TITLE
6sense integration

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#386]
Drive folder: https://drive.google.com/drive/u/0/folders/1wS6_KM0WZpmx70KQIL4ijRu9GWzuF7SH

- User connected on Monday 6th May
- Kick off Friday 10th May

**Comment by ruipperez** [comment]
**Augmenting SFDC:**
One item that wasn’t discussed during the kickoff is augmenting your salesforce with 6sense data. This is two mutually exclusive workflows. One is pushing 6sense scores to custom fields on the account, contact and lead object. The second is the installation of the 6sense application in SFDC to provide the platform as an iFrame in your Salesforce.

In order to complete these processes please follow the below instructions. Note, data will not be available until your model is ready, but you are able to set each of these up at your earliest convenience. Ideally, we will want this to be ready when your model is available so you have a couple weeks to complete this. Of the two items I would prioritize the app install (should only take ~30 minutes) as we will want this for the call following the model walkthrough discussion.

6sense App for SFDC:    
Install 6sense [APP](https://support.6sense.com/article-categories/installation-sales-intelligence/)- This step is designed to allow visibility into our Sales Intelligence iFrame and Out of the Box Dashboard Experiences. Your API key is: 525f36af1bf267ce2e3e21ee8e4fc81a3bd6faf2 
 

Score Export
Create Custom Fields: This set up is required to ensure we are pushing data to the correct fields inside your systems. [Learn more here](https://support.6sense.com/knowledge-base/360059850934-custom-fields-for-predictive-score-orchestrations/)
Setup Mapping Profile: This step is designed to ensure we push the right 6sense data to the right location in your systems. [Learn more here](https://support.6sense.com/knowledge-base/360045344214-setting-up-mapping-profiles/)
Enable Score Export Orchestrations: This orchestration helps automate pushing data into your associated CRM/MAP fields, properties, or custom data objects. Learn more here

**Comment by ruipperez** [comment]
Installation done in prod **May 14th.** 

Fields created **only** **in prod**: https://support.6sense.com/knowledge-base/360059850934-custom-fields-for-predictive-score-orchestrations/

**Model**: including NB with Close Date equal or greater 1/1/2023, excluding industries: Cities & Government & NGO

**Comment by ruipperez** [comment]
Model: https://docs.google.com/document/d/1rWYJRrzpSZOcCpCwxAtITyReiPpurdVQ/edit?usp=drive_web&ouid=100245791345403401959&rtpof=true

**Comment by MiriamMartinezNunez** [comment]
Closing here. Moved to Shortcut [https://app.shortcut.com/cartoteam/story/427349/6sense-integration]
