### ISSUE TITLE
DNB Integration

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#387]
Drive: https://drive.google.com/drive/u/0/folders/1ogjhA5AhZYBAOM28H8YZ6HMV-CZvIfjQ

**Comment by ruipperez** [comment]
@Brian - to have the meeting to go through the integration

**Comment by ruipperez** [comment]
Installation guide: https://drive.google.com/drive/u/0/folders/1q1f0JdPX_CGiRzCN7hNOB3TJuLnobJtW

**Comment by MiriamMartinezNunez** [comment]
Moved to Shortcut: https://app.shortcut.com/cartoteam/story/427326/dnb-integration
