### ISSUE TITLE
Gong<>SF integration (package)

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#388]
Installation done in **April 19th.**

Few issues reporting and being discussed with Support:

- Call Result is not consistently recorded
- There are Gong calls/meetings that are NOT creating Tasks.
Example: Conversation Seguiminento PwC-Cellnex-CARTO
- We've found some activities being registered in SF by Gong that are prior to the integration - If the Lead is modified, a past activity will be added in SF? Also, we can see that this is creating a Task but not. a Gong conversation (Gong object). Example: Eben Potgieter
- According to the Telephony Settings in Company Settings > Export to Salesforce as tasks, Gong should register as Tasks call attemps, calls unasnwered...
- Gong does not record calls below 30 seconds - any work around here? We have an example of a call that shows up in SF but it doesn't create a Task: https://us-10671.app.gong.io/call?id=195880760997210152&account-id=4169744685441176961
- The report Activity with Gong Related Leads doesn't seem to work.
I think it'd be easier if we could schedule a call and go through all these scenarios where we can show you all these examples in detail.

**Comment by MiriamMartinezNunez** [comment]
Moving to Shortcut and closing here [https://app.shortcut.com/cartoteam/story/427367]
